name: MMC Forge Electron Template
description: 'A modern Electron application template with React, Vite, TypeScript, Shadcn UI and TailwindCSS'
labels:
  - electron
  - react
  - typescript
  - vite
  - tailwindcss
  - shadcn-ui
  - desktop-app
  - mmcforge